services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5437:5432
    environment:
      POSTGRES_DB: pico
      POSTGRES_USER: pico
      POSTGRES_PASSWORD: pico1234
